# Generated by Django 5.0.2 on 2024-02-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.AddField(
            model_name='location',
            name='hydra_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
