# Generated by Django 5.0.2 on 2024-02-29 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbot', '0002_remove_location_country_location_hydra_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervizor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Чуйская', 'Чуйская'), ('Иссык-кульская', 'Иссык-кульская'), ('Нарынская', 'Нарынская'), ('Джалал-Абадская', 'Джалал-Абадская'), ('Баткенская', 'Баткенская'), ('Ошская', 'Ошская'), ('Таласская', 'Таласская')], max_length=50, verbose_name='Область')),
                ('supervizer_hydra_id', models.BigIntegerField(verbose_name='Супервайзер_ID')),
                ('supervizer_surname', models.CharField(max_length=100, verbose_name='ФИО супервайзера')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervizor', to=settings.AUTH_USER_MODEL, verbose_name='Супервайзер')),
            ],
            options={
                'verbose_name': 'Супервайзеры',
                'verbose_name_plural': 'Супервайзеры',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bx_id', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область')),
                ('supervizer', models.CharField(blank=True, max_length=10, null=True)),
                ('surname', models.CharField(max_length=50, verbose_name='ФИО агента')),
                ('hydra_id_sales', models.CharField(blank=True, max_length=50, verbose_name='Гидра_ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Агент')),
                ('supervizer_surname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='super_id', to='webbot.supervizor')),
            ],
            options={
                'verbose_name': 'Агенты',
                'verbose_name_plural': 'Агенты',
            },
        ),
    ]
