# Generated by Django 5.0.2 on 2024-02-29 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbot', '0003_supervizor_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='supervizer_surname',
        ),
        migrations.AddField(
            model_name='agent',
            name='supervizer_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='supervizer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='super_id', to='webbot.supervizor'),
            preserve_default=False,
        ),
    ]
