# Generated by Django 5.0.2 on 2024-02-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbot', '0005_alter_agent_supervizer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='hydra_id_sales',
            field=models.CharField(max_length=50, verbose_name='Гидра_ID'),
        ),
    ]
