# Generated by Django 5.0.2 on 2024-03-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbot', '0006_alter_agent_hydra_id_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='hydra_id_sales',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Гидра_ID'),
        ),
    ]
