# Generated by Django 5.0.2 on 2024-03-09 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbot', '0007_alter_agent_hydra_id_sales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Агент'),
        ),
        migrations.AlterField(
            model_name='supervizor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervizor', to=settings.AUTH_USER_MODEL, verbose_name='Супервайзер'),
        ),
    ]
