# Generated by Django 4.2.6 on 2024-03-11 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webbot', '0008_alter_agent_user_alter_supervizor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.CreateModel(
            name='Zayavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='new', max_length=10)),
                ('router_installation', models.CharField(default='router', max_length=10)),
                ('tariff', models.CharField(max_length=50)),
                ('super_tv_installation', models.CharField(default='tv', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('hydra_dogovor', models.CharField(max_length=100)),
                ('previous_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('primary_phone', models.CharField(max_length=20)),
                ('secondary_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('intercom_account', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('hydra_address', models.CharField(blank=True, max_length=100, null=True)),
                ('hydra_abbon_ls', models.CharField(blank=True, max_length=100, null=True)),
                ('passport_front_image_url', models.URLField(blank=True, null=True)),
                ('passport_back_image_url', models.URLField(blank=True, null=True)),
                ('location_url', models.URLField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='webbot.agent')),
            ],
            options={
                'verbose_name': 'Агенты',
                'verbose_name_plural': 'Агенты',
            },
        ),
    ]
