# Generated by Django 5.0.2 on 2024-03-11 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webbot', '0010_alter_zayavka_options_alter_zayavka_location_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
    ]
